# Generated by Django 4.1.5 on 2023-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Project Manager', 'PM'), ('Software Developer', 'SDE-1'), ('Team Leader', 'TL')], max_length=50),
        ),
    ]
